### PR TITLE
Translate Ukrainian locale from Russian to Ukrainian

### PR DESCRIPTION
**Pull request by rakvium**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Make Ukrainian locale using Ukrainian language instead of Russian
| Type?         | improvement
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | no
| How to test?  | :shrug:

### CODE REVIEW

**Comment by Progi1984** [comment]
Ping @LouiseBonnard & @Julievrz for your advice on this PR.

**Comment by Julievrz** [comment]
Hi @rakvium, I am not sure to understand your suggestion. I think I can see some little modifications. Are you saying that the part in red is written in Russian while it should be written in Ukrainian (green part)? 

image
image

I just want to make sure I understand as I don't speak Russian or Ukrainian. 

Thanks

**Comment by rakvium** [comment]
Hi @Julievrz, yes, it is a name of a tax. In English it's "VAT" (value-added tax). 
In Russian: "НДС" (налог на добавленную стоимость)
In Ukrainian: "ПДВ" (податок на додану вартість)

**Comment by Julievrz** [comment]
> Hi @Julievrz, yes, it is a name of a tax. In English it's "VAT" (value-added tax).
> In Russian: "НДС" (налог на добавленную стоимость)
> In Ukrainian: "ПДВ" (податок на додану вартість)

So you are saying that there is a mistake in the translation?

**Comment by rakvium** [comment]
@Julievrz I'm saying that this Ukrainian localization file is currently using Russian language instead of Ukrainian.

**Comment by Julievrz** [comment]
In that case, I think it should indeed be modified. I'll let @LouiseBonnard have a look. :)

**Comment by LouiseBonnard** [comment]
It is ✅, thanks @rakvium! @Julievrz, how about asking the Ukrainian proofreaders to have a quick look at it, - just to have a double-check and then test/merge this PR?

**Comment by Julievrz** [comment]
I have contacted a Ukrainian proofreader on Crowdin, I will let you know!

**Review by 0purple — APPROVED** [review]

**Comment by 0purple** [comment]
I`m Ukrainian native, this looks good to me

**Review by atomiix — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Comment by Progi1984** [comment]
@Julievrz Some news ?

**Comment by Julievrz** [comment]
@Progi1984 Unfortunately, I didn't get any answers. I think we can trust @0purple and @rakvium who are both Ukrainian natives.

**Comment by Progi1984** [comment]
@Julievrz Like it's ok for you, i can merge.

**Pull request merged**
