### PR TITLE
Update czech localization pack to reflect changes in the core

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Update czech localization pack to reflect recent changes in the core - https://github.com/PrestaShop/PrestaShop/blob/8.1.x/localization/cz.xml. Added new VAT rates, removed euro currency, removed states which are not states but just cities etc.
| Fixed ticket? |

### CODE REVIEW

**Review by matks — APPROVED** [review]
This change is reflecting changes in Pull Requests https://github.com/PrestaShop/PrestaShop/pull/33976/ and https://github.com/PrestaShop/PrestaShop/pull/34529/

**Comment by matks** [comment]
As these changes reflect PRs already merged in the Core, I consider the content has already been validated

**Comment by matks** [comment]
(mmmm I'm still asking some questions to @Hlavtox to be sure 😛 )

**Review by matks — APPROVED** [review]
Thank you @Hlavtox for answering all my questions 👍

**Comment by Hlavtox** [comment]
@matks Thank youuuu!

**Pull request merged**
