### PR TITLE
Update default tax rate for Finland, fixes #36712

### LINKED ISSUE #36712: Finland default VAT changes from 24% -> 25.5% on 1.9.2024
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The Finnish government has decided to up VAT from 24% to 25.5% on 1.9.2024. The default values in PrestaShop should reflect this change.

### Expected behavior

On new installation fetching the Finnish localization pack installs the correct VAT percent (25.5%) for general goods.

### Steps to reproduce

1. Install prestashop
2. Load Finnish localization pack
3. Check that finland general goods tax rate is 25.5%

### PrestaShop version(s) where the bug happened

-

### PHP version(s) where the bug happened

-

### If your bug is related to a module, specify its name and its version

-

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by tswfi**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Update Finnish tax matrix to reflect the increase from 24% to 25.5% starting on 1.9.2024
| Fixed ticket? | Fixes https://github.com/PrestaShop/PrestaShop/issues/36712

### CODE REVIEW

**Comment by ps-jarvis** [comment]
Hello @tswfi!

This is your first pull request on [LocalizationFiles](https://github.com/PrestaShop/LocalizationFiles/) repository of the PrestaShop project.

Thank you, and welcome to this Open Source community!

**Review by Hlavtox — APPROVED** [review]

**Review by matks — APPROVED** [review]
To be merged only on 1st of September, the files of this repo are mirrored LIVE on website https://i18n.prestashop.com/ which is used by shops all over the world to get up-to-date localization files

**Review by ShaiMagal — APPROVED** [review]

**Review by florine2623 — APPROVED** [review]
Hello @tswfi ,

Before :
`<tax id="12" name="ALV FI 24%" rate="24" auto-generated="1" from-eu-tax-group="virtual"/>`

After :
`<tax id="12" name="ALV FI 25.5%" rate="25.5" auto-generated="1" from-eu-tax-group="virtual"/>`

Screenshot 2024-08-28 at 16 18 59
Screenshot 2024-08-28 at 16 19 05

LGTM ✅ 

⚠️ TO BE MERGED ONLY ON SEPTEMBER 1ST ⚠️

**Comment by tswfi** [comment]
please merge this

**Comment by matks** [comment]
@tswfi Yes it's time 😄 I set up a reminder to make sure I would not forget

**Pull request merged**
