### PR TITLE
Add localization pack for Monaco

### LINKED ISSUE #22790: Missing localization pack for Monaco
#### Describe the bug

Orders placed to Monaco do not contain any tax.

#### Expected behavior

Orders placed to Monaco must respect the French VAT.

#### Steps to Reproduce

1. Place an order with delivery in Monaco
2. Prices are exclusive of VAT

I'll make a PR soon.

### PR DESCRIPTION
**Pull request by micka-fdz**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | This PR add localization pack for Monaco.
| Fixed ticket? | Fixes https://github.com/PrestaShop/PrestaShop/issues/22790

### CODE REVIEW

**Review by Progi1984 — APPROVED** [review]

**Comment by Progi1984** [comment]
Already approved in https://github.com/PrestaShop/PrestaShop/pull/22811

**Review by matks — APPROVED** [review]
I verified this PR content, localization files change are identical to https://github.com/PrestaShop/PrestaShop/pull/22811. https://github.com/PrestaShop/PrestaShop/pull/22811 has been validated by QA so this PR is valid too.

**Review by sowbiba — APPROVED** [review]
Looks good. I would be more comfurtable if a @PrestaShop/product-team  can review it, for the taxes

**Comment by micka-fdz** [comment]
Thanks @Progi1984, @matks and @sowbiba 👍

**Comment by Progi1984** [comment]
Thanks @micka-fdz 

As discussed with @florine2623 & @Robin-Fischer-PS, no need to a new QA check.

**Pull request merged**
